
# Настройки Zabbix
zabbix_version: "7.0"
zabbix_db_name: "zabbix"
zabbix_db_user: "zabbix"
zabbix_db_password: "zabbix"  # TODO: Переделать на vault или другой secure storage
zabbix_server: "zabbix.example.com"

# Настройки PHP
php_fpm_socket: "/var/run/php/php8.1-fpm.sock"

# Адреса ресурсов
zabbix_server_ip: zabbix.ru-central1.internal
bastion_ip: bastion.ru-central1.internal
weba_ip: web-a.ru-central1.internal
webb_ip: web-b.ru-central1.internal
elastic_ip: elastic.ru-central.internal
