---
- hosts: webservers
  become: yes
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create web content directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Create index page
      copy:
        content: |
          <html>
          <body>
          <h1>Welcome to my web server!</h1>
          </body>
          </html>
        dest: /var/www/html/index.html
