---
- hosts: zabbix
  become: yes
  tasks:
    - name: Download zabbix
      ansible.builtin.url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
        dest: /tmp/zabbix.deb

    - name: Install zabbix package
      ansible.builtin.apt:
        deb: /tmp/zabbix.deb

    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install zabbix-server-pgsql
      ansible.builtin.apt:
        name: zabbix-server-pgsql
        state: latest

    - name: Install zabbix-frontend-php
      ansible.builtin.apt:
        name: zabbix-frontend-php
        state: latest

    - name: Install php8.1-pgsql
      ansible.builtin.apt:
        name: php8.1-pgsql
        state: latest

    - name: Install zabbix-nginx-conf
      ansible.builtin.apt:
        name: zabbix-nginx-conf
        state: latest

    - name: Install zabbix-sql-scripts
      ansible.builtin.apt:
        name: zabbix-sql-scripts
        state: latest

    - name: Install zabbix-agent
      ansible.builtin.apt:
        name: zabbix-agent
        state: latest



